### PR TITLE
CI setup

### PR DESCRIPTION
**Pull request by mindplay-dk**
I added build status via TravisCI, code-coverage status via Coveralls, and badges in the README.

For this to work, you'll need to log into [TravisCI](https://travis-ci.org/) and enable builds for the repository - this should be helpful going forward, as Travis will build branches with active pull-requests, and we'll be able to see if a PR passes or breaks any tests.

You will need to log into [Coveralls](https://coveralls.io/) as well and add your GitHub repository to enable code coverage reporting - this is mainly for the badge, as it's nice for others to know how well the library is tested, but there's a report (if you scroll down) on that page as well, which gives a nice report, and it keeps track of code coverage progression (better/worse) between builds as well.

If you've never used either of these, don't worry - it's very easy to set up, and both services are free for open-source projects.

### CODE REVIEW

**Comment by mindplay-dk** [comment]
(By the way, I didn't actually mean to change all the single quotes `'` to double quotes `"` - that was an accidental search and replace. If you prefer, I can change it back.)

**Comment by 132yse** [comment]
That's Great!
Thank you very much!
> (By the way, I didn't actually mean to change all the single quotes ' to double quotes "
In fact, I prefer single quote,  but both are OK.

**Comment by 132yse** [comment]
Unfortunately, I found that https://travis-ci.org could not be opened in China.

Maybe we can use https://circleci.com？

**Comment by 132yse** [comment]
First of all, thank you very much for your efforts. This is the first time I have used the CI build tool.

But unfortunately, TravisCI is not accessible in China because of China's Great Firewall .

So I replaced travisCI with circleCI, which faster in China, It is the first choice for many Chinese open source developers.

**Pull request merged**
