### PR TITLE
use `setTimeout` instead of message-channel

### PR DESCRIPTION
**Pull request by mindplay-dk**
As mentioned in comments in #50 

Working sandbox [here](https://codesandbox.io/s/suspicious-rosalind-i06mv).

### CODE REVIEW

**Comment by 132yse** [comment]
Maybe setTimeOut can be a compatible API?

https://github.com/132yse/fre/pull/50#issuecomment-538441885

**Comment by 132yse** [comment]
I'm sorry that I start school today, and there is no computer for me now, so I will have performance tests for them when I get computer.

**Comment by 132yse** [comment]
In fact, I don't know the difference between `setTimeOut `  and  `Message Channel` .
Just to see that react is using Mesaage Channel, I also want to know why, maybe we need to open an issue at React repo?

**Comment by mindplay-dk** [comment]
I did a bit of research - I read [this](https://philippspiess.com/scheduling-in-react/) and finally came across this:

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

It confirms what you said:

> `setTimeout(fn, 0)` can potentially be used, however as it is **clamped to 4ms for timers** nested more than 5 levels deep per the HTML spec, **it does not make for a suitable polyfill** for the natural immediacy of `setImmediate`.

So I agree, there is currently no good option besides message channels - it's good to see that there is a proposal to add this feature, but `setImmediate` won't be available (through any other means besides a [polyfill](https://github.com/YuzuJS/setImmediate)) for a while, probably.

Closing this issue as my proposed change doesn't make sense.

**Comment by 132yse** [comment]
I think setTimeout can still be used as a compatible API for no-browser environments, such as Native, Fard.

**Comment by 132yse** [comment]
I reopen and merge it, then I will make it use as a compatible API

**Comment by mindplay-dk** [comment]
Oops, you probably shouldn't have merged this? The source control history will be a mess because of my broken Git - and now you have CRLF in the file. My fault, sorry! 😣

You should probably check out the previous commit and force push to `master` to undo this from source history?

**Comment by 132yse** [comment]
I have resolved all the conflicts. 😊

**Pull request merged**
